//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:41:40 AM CEST 
//


package models.economy;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TeamID"/>
 *         &lt;element ref="{}TeamName"/>
 *         &lt;element ref="{}Cash"/>
 *         &lt;element ref="{}ExpectedCash"/>
 *         &lt;element ref="{}SponsorsPopularity"/>
 *         &lt;element ref="{}SupportersPopularity"/>
 *         &lt;element ref="{}FanClubSize"/>
 *         &lt;element ref="{}IncomeSpectators"/>
 *         &lt;element ref="{}IncomeSponsors"/>
 *         &lt;element ref="{}IncomeFinancial"/>
 *         &lt;element ref="{}IncomeTemporary"/>
 *         &lt;element ref="{}IncomeSum"/>
 *         &lt;element ref="{}CostsArena"/>
 *         &lt;element ref="{}CostsPlayers"/>
 *         &lt;element ref="{}CostsFinancial"/>
 *         &lt;element ref="{}CostsStaff"/>
 *         &lt;element ref="{}CostsTemporary"/>
 *         &lt;element ref="{}CostsYouth"/>
 *         &lt;element ref="{}CostsSum"/>
 *         &lt;element ref="{}ExpectedWeeksTotal"/>
 *         &lt;element ref="{}LastIncomeSpectators"/>
 *         &lt;element ref="{}LastIncomeSponsors"/>
 *         &lt;element ref="{}LastIncomeFinancial"/>
 *         &lt;element ref="{}LastIncomeTemporary"/>
 *         &lt;element ref="{}LastIncomeSum"/>
 *         &lt;element ref="{}LastCostsArena"/>
 *         &lt;element ref="{}LastCostsPlayers"/>
 *         &lt;element ref="{}LastCostsFinancial"/>
 *         &lt;element ref="{}LastCostsStaff"/>
 *         &lt;element ref="{}LastCostsTemporary"/>
 *         &lt;element ref="{}LastCostsYouth"/>
 *         &lt;element ref="{}LastCostsSum"/>
 *         &lt;element ref="{}LastWeeksTotal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "teamID",
    "teamName",
    "cash",
    "expectedCash",
    "sponsorsPopularity",
    "supportersPopularity",
    "fanClubSize",
    "incomeSpectators",
    "incomeSponsors",
    "incomeFinancial",
    "incomeTemporary",
    "incomeSum",
    "costsArena",
    "costsPlayers",
    "costsFinancial",
    "costsStaff",
    "costsTemporary",
    "costsYouth",
    "costsSum",
    "expectedWeeksTotal",
    "lastIncomeSpectators",
    "lastIncomeSponsors",
    "lastIncomeFinancial",
    "lastIncomeTemporary",
    "lastIncomeSum",
    "lastCostsArena",
    "lastCostsPlayers",
    "lastCostsFinancial",
    "lastCostsStaff",
    "lastCostsTemporary",
    "lastCostsYouth",
    "lastCostsSum",
    "lastWeeksTotal"
})
@XmlRootElement(name = "Team")
public class Team {

    @XmlElement(name = "TeamID", required = true)
    protected BigInteger teamID;
    @XmlElement(name = "TeamName", required = true)
    protected String teamName;
    @XmlElement(name = "Cash", required = true)
    protected BigInteger cash;
    @XmlElement(name = "ExpectedCash", required = true)
    protected BigInteger expectedCash;
    @XmlElement(name = "SponsorsPopularity", required = true)
    protected SponsorsPopularity sponsorsPopularity;
    @XmlElement(name = "SupportersPopularity", required = true)
    protected SupportersPopularity supportersPopularity;
    @XmlElement(name = "FanClubSize", required = true)
    protected BigInteger fanClubSize;
    @XmlElement(name = "IncomeSpectators", required = true)
    protected BigInteger incomeSpectators;
    @XmlElement(name = "IncomeSponsors", required = true)
    protected BigInteger incomeSponsors;
    @XmlElement(name = "IncomeFinancial", required = true)
    protected BigInteger incomeFinancial;
    @XmlElement(name = "IncomeTemporary", required = true)
    protected BigInteger incomeTemporary;
    @XmlElement(name = "IncomeSum", required = true)
    protected BigInteger incomeSum;
    @XmlElement(name = "CostsArena", required = true)
    protected BigInteger costsArena;
    @XmlElement(name = "CostsPlayers", required = true)
    protected BigInteger costsPlayers;
    @XmlElement(name = "CostsFinancial", required = true)
    protected BigInteger costsFinancial;
    @XmlElement(name = "CostsStaff", required = true)
    protected BigInteger costsStaff;
    @XmlElement(name = "CostsTemporary", required = true)
    protected BigInteger costsTemporary;
    @XmlElement(name = "CostsYouth", required = true)
    protected BigInteger costsYouth;
    @XmlElement(name = "CostsSum", required = true)
    protected BigInteger costsSum;
    @XmlElement(name = "ExpectedWeeksTotal", required = true)
    protected BigInteger expectedWeeksTotal;
    @XmlElement(name = "LastIncomeSpectators", required = true)
    protected BigInteger lastIncomeSpectators;
    @XmlElement(name = "LastIncomeSponsors", required = true)
    protected BigInteger lastIncomeSponsors;
    @XmlElement(name = "LastIncomeFinancial", required = true)
    protected BigInteger lastIncomeFinancial;
    @XmlElement(name = "LastIncomeTemporary", required = true)
    protected BigInteger lastIncomeTemporary;
    @XmlElement(name = "LastIncomeSum", required = true)
    protected BigInteger lastIncomeSum;
    @XmlElement(name = "LastCostsArena", required = true)
    protected BigInteger lastCostsArena;
    @XmlElement(name = "LastCostsPlayers", required = true)
    protected BigInteger lastCostsPlayers;
    @XmlElement(name = "LastCostsFinancial", required = true)
    protected BigInteger lastCostsFinancial;
    @XmlElement(name = "LastCostsStaff", required = true)
    protected BigInteger lastCostsStaff;
    @XmlElement(name = "LastCostsTemporary", required = true)
    protected BigInteger lastCostsTemporary;
    @XmlElement(name = "LastCostsYouth", required = true)
    protected BigInteger lastCostsYouth;
    @XmlElement(name = "LastCostsSum", required = true)
    protected BigInteger lastCostsSum;
    @XmlElement(name = "LastWeeksTotal", required = true)
    protected BigInteger lastWeeksTotal;

    /**
     * Gets the value of the teamID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTeamID() {
        return teamID;
    }

    /**
     * Sets the value of the teamID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTeamID(BigInteger value) {
        this.teamID = value;
    }

    /**
     * Gets the value of the teamName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * Sets the value of the teamName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamName(String value) {
        this.teamName = value;
    }

    /**
     * Gets the value of the cash property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCash() {
        return cash;
    }

    /**
     * Sets the value of the cash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCash(BigInteger value) {
        this.cash = value;
    }

    /**
     * Gets the value of the expectedCash property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExpectedCash() {
        return expectedCash;
    }

    /**
     * Sets the value of the expectedCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExpectedCash(BigInteger value) {
        this.expectedCash = value;
    }

    /**
     * Gets the value of the sponsorsPopularity property.
     * 
     * @return
     *     possible object is
     *     {@link SponsorsPopularity }
     *     
     */
    public SponsorsPopularity getSponsorsPopularity() {
        return sponsorsPopularity;
    }

    /**
     * Sets the value of the sponsorsPopularity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SponsorsPopularity }
     *     
     */
    public void setSponsorsPopularity(SponsorsPopularity value) {
        this.sponsorsPopularity = value;
    }

    /**
     * Gets the value of the supportersPopularity property.
     * 
     * @return
     *     possible object is
     *     {@link SupportersPopularity }
     *     
     */
    public SupportersPopularity getSupportersPopularity() {
        return supportersPopularity;
    }

    /**
     * Sets the value of the supportersPopularity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupportersPopularity }
     *     
     */
    public void setSupportersPopularity(SupportersPopularity value) {
        this.supportersPopularity = value;
    }

    /**
     * Gets the value of the fanClubSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFanClubSize() {
        return fanClubSize;
    }

    /**
     * Sets the value of the fanClubSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFanClubSize(BigInteger value) {
        this.fanClubSize = value;
    }

    /**
     * Gets the value of the incomeSpectators property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIncomeSpectators() {
        return incomeSpectators;
    }

    /**
     * Sets the value of the incomeSpectators property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIncomeSpectators(BigInteger value) {
        this.incomeSpectators = value;
    }

    /**
     * Gets the value of the incomeSponsors property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIncomeSponsors() {
        return incomeSponsors;
    }

    /**
     * Sets the value of the incomeSponsors property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIncomeSponsors(BigInteger value) {
        this.incomeSponsors = value;
    }

    /**
     * Gets the value of the incomeFinancial property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIncomeFinancial() {
        return incomeFinancial;
    }

    /**
     * Sets the value of the incomeFinancial property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIncomeFinancial(BigInteger value) {
        this.incomeFinancial = value;
    }

    /**
     * Gets the value of the incomeTemporary property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIncomeTemporary() {
        return incomeTemporary;
    }

    /**
     * Sets the value of the incomeTemporary property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIncomeTemporary(BigInteger value) {
        this.incomeTemporary = value;
    }

    /**
     * Gets the value of the incomeSum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIncomeSum() {
        return incomeSum;
    }

    /**
     * Sets the value of the incomeSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIncomeSum(BigInteger value) {
        this.incomeSum = value;
    }

    /**
     * Gets the value of the costsArena property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCostsArena() {
        return costsArena;
    }

    /**
     * Sets the value of the costsArena property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCostsArena(BigInteger value) {
        this.costsArena = value;
    }

    /**
     * Gets the value of the costsPlayers property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCostsPlayers() {
        return costsPlayers;
    }

    /**
     * Sets the value of the costsPlayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCostsPlayers(BigInteger value) {
        this.costsPlayers = value;
    }

    /**
     * Gets the value of the costsFinancial property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCostsFinancial() {
        return costsFinancial;
    }

    /**
     * Sets the value of the costsFinancial property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCostsFinancial(BigInteger value) {
        this.costsFinancial = value;
    }

    /**
     * Gets the value of the costsStaff property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCostsStaff() {
        return costsStaff;
    }

    /**
     * Sets the value of the costsStaff property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCostsStaff(BigInteger value) {
        this.costsStaff = value;
    }

    /**
     * Gets the value of the costsTemporary property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCostsTemporary() {
        return costsTemporary;
    }

    /**
     * Sets the value of the costsTemporary property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCostsTemporary(BigInteger value) {
        this.costsTemporary = value;
    }

    /**
     * Gets the value of the costsYouth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCostsYouth() {
        return costsYouth;
    }

    /**
     * Sets the value of the costsYouth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCostsYouth(BigInteger value) {
        this.costsYouth = value;
    }

    /**
     * Gets the value of the costsSum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCostsSum() {
        return costsSum;
    }

    /**
     * Sets the value of the costsSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCostsSum(BigInteger value) {
        this.costsSum = value;
    }

    /**
     * Gets the value of the expectedWeeksTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExpectedWeeksTotal() {
        return expectedWeeksTotal;
    }

    /**
     * Sets the value of the expectedWeeksTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExpectedWeeksTotal(BigInteger value) {
        this.expectedWeeksTotal = value;
    }

    /**
     * Gets the value of the lastIncomeSpectators property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastIncomeSpectators() {
        return lastIncomeSpectators;
    }

    /**
     * Sets the value of the lastIncomeSpectators property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastIncomeSpectators(BigInteger value) {
        this.lastIncomeSpectators = value;
    }

    /**
     * Gets the value of the lastIncomeSponsors property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastIncomeSponsors() {
        return lastIncomeSponsors;
    }

    /**
     * Sets the value of the lastIncomeSponsors property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastIncomeSponsors(BigInteger value) {
        this.lastIncomeSponsors = value;
    }

    /**
     * Gets the value of the lastIncomeFinancial property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastIncomeFinancial() {
        return lastIncomeFinancial;
    }

    /**
     * Sets the value of the lastIncomeFinancial property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastIncomeFinancial(BigInteger value) {
        this.lastIncomeFinancial = value;
    }

    /**
     * Gets the value of the lastIncomeTemporary property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastIncomeTemporary() {
        return lastIncomeTemporary;
    }

    /**
     * Sets the value of the lastIncomeTemporary property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastIncomeTemporary(BigInteger value) {
        this.lastIncomeTemporary = value;
    }

    /**
     * Gets the value of the lastIncomeSum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastIncomeSum() {
        return lastIncomeSum;
    }

    /**
     * Sets the value of the lastIncomeSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastIncomeSum(BigInteger value) {
        this.lastIncomeSum = value;
    }

    /**
     * Gets the value of the lastCostsArena property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastCostsArena() {
        return lastCostsArena;
    }

    /**
     * Sets the value of the lastCostsArena property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastCostsArena(BigInteger value) {
        this.lastCostsArena = value;
    }

    /**
     * Gets the value of the lastCostsPlayers property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastCostsPlayers() {
        return lastCostsPlayers;
    }

    /**
     * Sets the value of the lastCostsPlayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastCostsPlayers(BigInteger value) {
        this.lastCostsPlayers = value;
    }

    /**
     * Gets the value of the lastCostsFinancial property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastCostsFinancial() {
        return lastCostsFinancial;
    }

    /**
     * Sets the value of the lastCostsFinancial property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastCostsFinancial(BigInteger value) {
        this.lastCostsFinancial = value;
    }

    /**
     * Gets the value of the lastCostsStaff property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastCostsStaff() {
        return lastCostsStaff;
    }

    /**
     * Sets the value of the lastCostsStaff property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastCostsStaff(BigInteger value) {
        this.lastCostsStaff = value;
    }

    /**
     * Gets the value of the lastCostsTemporary property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastCostsTemporary() {
        return lastCostsTemporary;
    }

    /**
     * Sets the value of the lastCostsTemporary property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastCostsTemporary(BigInteger value) {
        this.lastCostsTemporary = value;
    }

    /**
     * Gets the value of the lastCostsYouth property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastCostsYouth() {
        return lastCostsYouth;
    }

    /**
     * Sets the value of the lastCostsYouth property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastCostsYouth(BigInteger value) {
        this.lastCostsYouth = value;
    }

    /**
     * Gets the value of the lastCostsSum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastCostsSum() {
        return lastCostsSum;
    }

    /**
     * Sets the value of the lastCostsSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastCostsSum(BigInteger value) {
        this.lastCostsSum = value;
    }

    /**
     * Gets the value of the lastWeeksTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastWeeksTotal() {
        return lastWeeksTotal;
    }

    /**
     * Sets the value of the lastWeeksTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastWeeksTotal(BigInteger value) {
        this.lastWeeksTotal = value;
    }

}
