//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.26 at 08:23:39 PM CET 
//


package models.achivements;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FileName"/>
 *         &lt;element ref="{}Version"/>
 *         &lt;element ref="{}UserID"/>
 *         &lt;element ref="{}FetchedDate"/>
 *         &lt;element ref="{}MaxPoints"/>
 *         &lt;element ref="{}AchievementList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileName",
    "version",
    "userID",
    "fetchedDate",
    "maxPoints",
    "achievementList"
})
@XmlRootElement(name = "HattrickData")
public class HattrickData {

    @XmlElement(name = "FileName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fileName;
    @XmlElement(name = "Version", required = true)
    protected BigDecimal version;
    @XmlElement(name = "UserID", required = true)
    protected BigInteger userID;
    @XmlElement(name = "FetchedDate", required = true)
    protected String fetchedDate;
    @XmlElement(name = "MaxPoints", required = true)
    protected BigInteger maxPoints;
    @XmlElement(name = "AchievementList", required = true)
    protected AchievementList achievementList;

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserID(BigInteger value) {
        this.userID = value;
    }

    /**
     * Gets the value of the fetchedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFetchedDate() {
        return fetchedDate;
    }

    /**
     * Sets the value of the fetchedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFetchedDate(String value) {
        this.fetchedDate = value;
    }

    /**
     * Gets the value of the maxPoints property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxPoints() {
        return maxPoints;
    }

    /**
     * Sets the value of the maxPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxPoints(BigInteger value) {
        this.maxPoints = value;
    }

    /**
     * Gets the value of the achievementList property.
     * 
     * @return
     *     possible object is
     *     {@link AchievementList }
     *     
     */
    public AchievementList getAchievementList() {
        return achievementList;
    }

    /**
     * Sets the value of the achievementList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AchievementList }
     *     
     */
    public void setAchievementList(AchievementList value) {
        this.achievementList = value;
    }

}
