//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.26 at 08:23:39 PM CET 
//


package models.achivements;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FetchedDate_QNAME = new QName("", "FetchedDate");
    private final static QName _CategoryID_QNAME = new QName("", "CategoryID");
    private final static QName _FileName_QNAME = new QName("", "FileName");
    private final static QName _AchievementText_QNAME = new QName("", "AchievementText");
    private final static QName _NumberOfEvents_QNAME = new QName("", "NumberOfEvents");
    private final static QName _MultiLevel_QNAME = new QName("", "MultiLevel");
    private final static QName _UserID_QNAME = new QName("", "UserID");
    private final static QName _Points_QNAME = new QName("", "Points");
    private final static QName _Version_QNAME = new QName("", "Version");
    private final static QName _EventDate_QNAME = new QName("", "EventDate");
    private final static QName _MaxPoints_QNAME = new QName("", "MaxPoints");
    private final static QName _AchievementTypeID_QNAME = new QName("", "AchievementTypeID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Achievement }
     * 
     */
    public Achievement createAchievement() {
        return new Achievement();
    }

    /**
     * Create an instance of {@link AchievementList }
     * 
     */
    public AchievementList createAchievementList() {
        return new AchievementList();
    }

    /**
     * Create an instance of {@link HattrickData }
     * 
     */
    public HattrickData createHattrickData() {
        return new HattrickData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FetchedDate")
    public JAXBElement<String> createFetchedDate(String value) {
        return new JAXBElement<String>(_FetchedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CategoryID")
    public JAXBElement<BigInteger> createCategoryID(BigInteger value) {
        return new JAXBElement<BigInteger>(_CategoryID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FileName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFileName(String value) {
        return new JAXBElement<String>(_FileName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AchievementText")
    public JAXBElement<String> createAchievementText(String value) {
        return new JAXBElement<String>(_AchievementText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NumberOfEvents")
    public JAXBElement<BigInteger> createNumberOfEvents(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumberOfEvents_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MultiLevel")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMultiLevel(String value) {
        return new JAXBElement<String>(_MultiLevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserID")
    public JAXBElement<BigInteger> createUserID(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Points")
    public JAXBElement<BigInteger> createPoints(BigInteger value) {
        return new JAXBElement<BigInteger>(_Points_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Version")
    public JAXBElement<BigDecimal> createVersion(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Version_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EventDate")
    public JAXBElement<String> createEventDate(String value) {
        return new JAXBElement<String>(_EventDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MaxPoints")
    public JAXBElement<BigInteger> createMaxPoints(BigInteger value) {
        return new JAXBElement<BigInteger>(_MaxPoints_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AchievementTypeID")
    public JAXBElement<BigInteger> createAchievementTypeID(BigInteger value) {
        return new JAXBElement<BigInteger>(_AchievementTypeID_QNAME, BigInteger.class, null, value);
    }

}
