//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:41:26 AM CEST 
//


package models.club;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Physiotherapists_QNAME = new QName("", "Physiotherapists");
    private final static QName _FetchedDate_QNAME = new QName("", "FetchedDate");
    private final static QName _Economists_QNAME = new QName("", "Economists");
    private final static QName _Psychologists_QNAME = new QName("", "Psychologists");
    private final static QName _UserID_QNAME = new QName("", "UserID");
    private final static QName _HasPromoted_QNAME = new QName("", "HasPromoted");
    private final static QName _PressSpokesmen_QNAME = new QName("", "PressSpokesmen");
    private final static QName _TeamName_QNAME = new QName("", "TeamName");
    private final static QName _KeeperTrainers_QNAME = new QName("", "KeeperTrainers");
    private final static QName _TeamID_QNAME = new QName("", "TeamID");
    private final static QName _AssistantTrainers_QNAME = new QName("", "AssistantTrainers");
    private final static QName _Doctors_QNAME = new QName("", "Doctors");
    private final static QName _FileName_QNAME = new QName("", "FileName");
    private final static QName _YouthLevel_QNAME = new QName("", "YouthLevel");
    private final static QName _Investment_QNAME = new QName("", "Investment");
    private final static QName _Version_QNAME = new QName("", "Version");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link YouthSquad }
     * 
     */
    public YouthSquad createYouthSquad() {
        return new YouthSquad();
    }

    /**
     * Create an instance of {@link Specialists }
     * 
     */
    public Specialists createSpecialists() {
        return new Specialists();
    }

    /**
     * Create an instance of {@link HattrickData }
     * 
     */
    public HattrickData createHattrickData() {
        return new HattrickData();
    }

    /**
     * Create an instance of {@link Team }
     * 
     */
    public Team createTeam() {
        return new Team();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Physiotherapists")
    public JAXBElement<BigInteger> createPhysiotherapists(BigInteger value) {
        return new JAXBElement<BigInteger>(_Physiotherapists_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FetchedDate")
    public JAXBElement<String> createFetchedDate(String value) {
        return new JAXBElement<String>(_FetchedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Economists")
    public JAXBElement<BigInteger> createEconomists(BigInteger value) {
        return new JAXBElement<BigInteger>(_Economists_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Psychologists")
    public JAXBElement<BigInteger> createPsychologists(BigInteger value) {
        return new JAXBElement<BigInteger>(_Psychologists_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserID")
    public JAXBElement<BigInteger> createUserID(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HasPromoted")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createHasPromoted(String value) {
        return new JAXBElement<String>(_HasPromoted_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PressSpokesmen")
    public JAXBElement<BigInteger> createPressSpokesmen(BigInteger value) {
        return new JAXBElement<BigInteger>(_PressSpokesmen_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TeamName")
    public JAXBElement<String> createTeamName(String value) {
        return new JAXBElement<String>(_TeamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "KeeperTrainers")
    public JAXBElement<BigInteger> createKeeperTrainers(BigInteger value) {
        return new JAXBElement<BigInteger>(_KeeperTrainers_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TeamID")
    public JAXBElement<BigInteger> createTeamID(BigInteger value) {
        return new JAXBElement<BigInteger>(_TeamID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AssistantTrainers")
    public JAXBElement<BigInteger> createAssistantTrainers(BigInteger value) {
        return new JAXBElement<BigInteger>(_AssistantTrainers_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Doctors")
    public JAXBElement<BigInteger> createDoctors(BigInteger value) {
        return new JAXBElement<BigInteger>(_Doctors_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FileName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFileName(String value) {
        return new JAXBElement<String>(_FileName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "YouthLevel")
    public JAXBElement<BigInteger> createYouthLevel(BigInteger value) {
        return new JAXBElement<BigInteger>(_YouthLevel_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Investment")
    public JAXBElement<BigInteger> createInvestment(BigInteger value) {
        return new JAXBElement<BigInteger>(_Investment_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Version")
    public JAXBElement<BigDecimal> createVersion(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Version_QNAME, BigDecimal.class, null, value);
    }

}
