//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:46:09 AM CEST 
//


package models.matchlineup;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MatchType_QNAME = new QName("", "MatchType");
    private final static QName _FetchedDate_QNAME = new QName("", "FetchedDate");
    private final static QName _AwayTeamID_QNAME = new QName("", "AwayTeamID");
    private final static QName _IsYouth_QNAME = new QName("", "IsYouth");
    private final static QName _Behaviour_QNAME = new QName("", "Behaviour");
    private final static QName _RoleID_QNAME = new QName("", "RoleID");
    private final static QName _UserID_QNAME = new QName("", "UserID");
    private final static QName _MatchDate_QNAME = new QName("", "MatchDate");
    private final static QName _ArenaName_QNAME = new QName("", "ArenaName");
    private final static QName _PlayerName_QNAME = new QName("", "PlayerName");
    private final static QName _PositionCode_QNAME = new QName("", "PositionCode");
    private final static QName _AwayTeamName_QNAME = new QName("", "AwayTeamName");
    private final static QName _HomeTeamName_QNAME = new QName("", "HomeTeamName");
    private final static QName _ExperienceLevel_QNAME = new QName("", "ExperienceLevel");
    private final static QName _TeamName_QNAME = new QName("", "TeamName");
    private final static QName _TeamID_QNAME = new QName("", "TeamID");
    private final static QName _FileName_QNAME = new QName("", "FileName");
    private final static QName _Version_QNAME = new QName("", "Version");
    private final static QName _MatchID_QNAME = new QName("", "MatchID");
    private final static QName _HomeTeamID_QNAME = new QName("", "HomeTeamID");
    private final static QName _ArenaID_QNAME = new QName("", "ArenaID");
    private final static QName _PlayerID_QNAME = new QName("", "PlayerID");
    private final static QName _RatingStars_QNAME = new QName("", "RatingStars");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Lineup }
     * 
     */
    public Lineup createLineup() {
        return new Lineup();
    }

    /**
     * Create an instance of {@link AwayTeam }
     * 
     */
    public AwayTeam createAwayTeam() {
        return new AwayTeam();
    }

    /**
     * Create an instance of {@link Player }
     * 
     */
    public Player createPlayer() {
        return new Player();
    }

    /**
     * Create an instance of {@link Arena }
     * 
     */
    public Arena createArena() {
        return new Arena();
    }

    /**
     * Create an instance of {@link HattrickData }
     * 
     */
    public HattrickData createHattrickData() {
        return new HattrickData();
    }

    /**
     * Create an instance of {@link HomeTeam }
     * 
     */
    public HomeTeam createHomeTeam() {
        return new HomeTeam();
    }

    /**
     * Create an instance of {@link Team }
     * 
     */
    public Team createTeam() {
        return new Team();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MatchType")
    public JAXBElement<BigInteger> createMatchType(BigInteger value) {
        return new JAXBElement<BigInteger>(_MatchType_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FetchedDate")
    public JAXBElement<String> createFetchedDate(String value) {
        return new JAXBElement<String>(_FetchedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AwayTeamID")
    public JAXBElement<BigInteger> createAwayTeamID(BigInteger value) {
        return new JAXBElement<BigInteger>(_AwayTeamID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsYouth")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIsYouth(String value) {
        return new JAXBElement<String>(_IsYouth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Behaviour")
    public JAXBElement<BigInteger> createBehaviour(BigInteger value) {
        return new JAXBElement<BigInteger>(_Behaviour_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RoleID")
    public JAXBElement<BigInteger> createRoleID(BigInteger value) {
        return new JAXBElement<BigInteger>(_RoleID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserID")
    public JAXBElement<BigInteger> createUserID(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MatchDate")
    public JAXBElement<String> createMatchDate(String value) {
        return new JAXBElement<String>(_MatchDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArenaName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createArenaName(String value) {
        return new JAXBElement<String>(_ArenaName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PlayerName")
    public JAXBElement<String> createPlayerName(String value) {
        return new JAXBElement<String>(_PlayerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PositionCode")
    public JAXBElement<BigInteger> createPositionCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_PositionCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AwayTeamName")
    public JAXBElement<String> createAwayTeamName(String value) {
        return new JAXBElement<String>(_AwayTeamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HomeTeamName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createHomeTeamName(String value) {
        return new JAXBElement<String>(_HomeTeamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExperienceLevel")
    public JAXBElement<BigInteger> createExperienceLevel(BigInteger value) {
        return new JAXBElement<BigInteger>(_ExperienceLevel_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TeamName")
    public JAXBElement<String> createTeamName(String value) {
        return new JAXBElement<String>(_TeamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TeamID")
    public JAXBElement<BigInteger> createTeamID(BigInteger value) {
        return new JAXBElement<BigInteger>(_TeamID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FileName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFileName(String value) {
        return new JAXBElement<String>(_FileName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Version")
    public JAXBElement<BigDecimal> createVersion(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Version_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MatchID")
    public JAXBElement<BigInteger> createMatchID(BigInteger value) {
        return new JAXBElement<BigInteger>(_MatchID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HomeTeamID")
    public JAXBElement<BigInteger> createHomeTeamID(BigInteger value) {
        return new JAXBElement<BigInteger>(_HomeTeamID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArenaID")
    public JAXBElement<BigInteger> createArenaID(BigInteger value) {
        return new JAXBElement<BigInteger>(_ArenaID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PlayerID")
    public JAXBElement<BigInteger> createPlayerID(BigInteger value) {
        return new JAXBElement<BigInteger>(_PlayerID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RatingStars")
    public JAXBElement<BigDecimal> createRatingStars(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RatingStars_QNAME, BigDecimal.class, null, value);
    }

}
