//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:42:52 AM CEST 
//


package models.leaguedetails;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FileName"/>
 *         &lt;element ref="{}Version"/>
 *         &lt;element ref="{}UserID"/>
 *         &lt;element ref="{}FetchedDate"/>
 *         &lt;element ref="{}LeagueID"/>
 *         &lt;element ref="{}LeagueName"/>
 *         &lt;element ref="{}LeagueLevel"/>
 *         &lt;element ref="{}MaxLevel"/>
 *         &lt;element ref="{}LeagueLevelUnitID"/>
 *         &lt;element ref="{}LeagueLevelUnitName"/>
 *         &lt;element ref="{}Team" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fileName",
    "version",
    "userID",
    "fetchedDate",
    "leagueID",
    "leagueName",
    "leagueLevel",
    "maxLevel",
    "leagueLevelUnitID",
    "leagueLevelUnitName",
    "team"
})
@XmlRootElement(name = "HattrickData")
public class HattrickData {

    @XmlElement(name = "FileName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fileName;
    @XmlElement(name = "Version", required = true)
    protected BigDecimal version;
    @XmlElement(name = "UserID", required = true)
    protected BigInteger userID;
    @XmlElement(name = "FetchedDate", required = true)
    protected String fetchedDate;
    @XmlElement(name = "LeagueID", required = true)
    protected BigInteger leagueID;
    @XmlElement(name = "LeagueName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String leagueName;
    @XmlElement(name = "LeagueLevel", required = true)
    protected BigInteger leagueLevel;
    @XmlElement(name = "MaxLevel", required = true)
    protected BigInteger maxLevel;
    @XmlElement(name = "LeagueLevelUnitID", required = true)
    protected BigInteger leagueLevelUnitID;
    @XmlElement(name = "LeagueLevelUnitName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String leagueLevelUnitName;
    @XmlElement(name = "Team", required = true)
    protected List<Team> team;

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

    /**
     * Gets the value of the userID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUserID() {
        return userID;
    }

    /**
     * Sets the value of the userID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUserID(BigInteger value) {
        this.userID = value;
    }

    /**
     * Gets the value of the fetchedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFetchedDate() {
        return fetchedDate;
    }

    /**
     * Sets the value of the fetchedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFetchedDate(String value) {
        this.fetchedDate = value;
    }

    /**
     * Gets the value of the leagueID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLeagueID() {
        return leagueID;
    }

    /**
     * Sets the value of the leagueID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLeagueID(BigInteger value) {
        this.leagueID = value;
    }

    /**
     * Gets the value of the leagueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeagueName() {
        return leagueName;
    }

    /**
     * Sets the value of the leagueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeagueName(String value) {
        this.leagueName = value;
    }

    /**
     * Gets the value of the leagueLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLeagueLevel() {
        return leagueLevel;
    }

    /**
     * Sets the value of the leagueLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLeagueLevel(BigInteger value) {
        this.leagueLevel = value;
    }

    /**
     * Gets the value of the maxLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxLevel() {
        return maxLevel;
    }

    /**
     * Sets the value of the maxLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxLevel(BigInteger value) {
        this.maxLevel = value;
    }

    /**
     * Gets the value of the leagueLevelUnitID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLeagueLevelUnitID() {
        return leagueLevelUnitID;
    }

    /**
     * Sets the value of the leagueLevelUnitID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLeagueLevelUnitID(BigInteger value) {
        this.leagueLevelUnitID = value;
    }

    /**
     * Gets the value of the leagueLevelUnitName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeagueLevelUnitName() {
        return leagueLevelUnitName;
    }

    /**
     * Sets the value of the leagueLevelUnitName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeagueLevelUnitName(String value) {
        this.leagueLevelUnitName = value;
    }

    /**
     * Gets the value of the team property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the team property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTeam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Team }
     * 
     * 
     */
    public List<Team> getTeam() {
        if (team == null) {
            team = new ArrayList<Team>();
        }
        return this.team;
    }

}
