//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:49:08 AM CEST 
//


package models.teamdetails;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TeamID"/>
 *         &lt;element ref="{}TeamName"/>
 *         &lt;element ref="{}ShortTeamName"/>
 *         &lt;element ref="{}Arena"/>
 *         &lt;element ref="{}League"/>
 *         &lt;element ref="{}Region"/>
 *         &lt;element ref="{}Trainer"/>
 *         &lt;element ref="{}HomePage"/>
 *         &lt;element ref="{}DressURI"/>
 *         &lt;element ref="{}DressAlternateURI"/>
 *         &lt;element ref="{}LeagueLevelUnit"/>
 *         &lt;element ref="{}BotStatus"/>
 *         &lt;element ref="{}Cup"/>
 *         &lt;element ref="{}FriendlyTeamID"/>
 *         &lt;element ref="{}NumberOfVictories"/>
 *         &lt;element ref="{}NumberOfUndefeated"/>
 *         &lt;element ref="{}TeamRank"/>
 *         &lt;element ref="{}LogoURL"/>
 *         &lt;element ref="{}Fanclub"/>
 *         &lt;element ref="{}Guestbook"/>
 *         &lt;element ref="{}PressAnnouncement"/>
 *         &lt;element ref="{}YouthTeamID"/>
 *         &lt;element ref="{}YouthTeamName"/>
 *         &lt;element ref="{}NumberOfVisits"/>
 *         &lt;element ref="{}Flags"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "teamID",
    "teamName",
    "shortTeamName",
    "arena",
    "league",
    "region",
    "trainer",
    "homePage",
    "dressURI",
    "dressAlternateURI",
    "leagueLevelUnit",
    "botStatus",
    "cup",
    "friendlyTeamID",
    "numberOfVictories",
    "numberOfUndefeated",
    "teamRank",
    "logoURL",
    "fanclub",
    "guestbook",
    "pressAnnouncement",
    "youthTeamID",
    "youthTeamName",
    "numberOfVisits",
    "flags"
})
@XmlRootElement(name = "Team")
public class Team {

    @XmlElement(name = "TeamID", required = true)
    protected BigInteger teamID;
    @XmlElement(name = "TeamName", required = true)
    protected String teamName;
    @XmlElement(name = "ShortTeamName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String shortTeamName;
    @XmlElement(name = "Arena", required = true)
    protected Arena arena;
    @XmlElement(name = "League", required = true)
    protected League league;
    @XmlElement(name = "Region", required = true)
    protected Region region;
    @XmlElement(name = "Trainer", required = true)
    protected Trainer trainer;
    @XmlElement(name = "HomePage", required = true)
    protected HomePage homePage;
    @XmlElement(name = "DressURI", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String dressURI;
    @XmlElement(name = "DressAlternateURI", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String dressAlternateURI;
    @XmlElement(name = "LeagueLevelUnit", required = true)
    protected LeagueLevelUnit leagueLevelUnit;
    @XmlElement(name = "BotStatus", required = true)
    protected BotStatus botStatus;
    @XmlElement(name = "Cup", required = true)
    protected Cup cup;
    @XmlElement(name = "FriendlyTeamID", required = true)
    protected BigInteger friendlyTeamID;
    @XmlElement(name = "NumberOfVictories", required = true)
    protected BigInteger numberOfVictories;
    @XmlElement(name = "NumberOfUndefeated", required = true)
    protected BigInteger numberOfUndefeated;
    @XmlElement(name = "TeamRank", required = true)
    protected BigInteger teamRank;
    @XmlElement(name = "LogoURL", required = true)
    protected LogoURL logoURL;
    @XmlElement(name = "Fanclub", required = true)
    protected Fanclub fanclub;
    @XmlElement(name = "Guestbook", required = true)
    protected Guestbook guestbook;
    @XmlElement(name = "PressAnnouncement", required = true)
    protected PressAnnouncement pressAnnouncement;
    @XmlElement(name = "YouthTeamID", required = true)
    protected BigInteger youthTeamID;
    @XmlElement(name = "YouthTeamName", required = true)
    protected String youthTeamName;
    @XmlElement(name = "NumberOfVisits", required = true)
    protected BigInteger numberOfVisits;
    @XmlElement(name = "Flags", required = true)
    protected Flags flags;

    /**
     * Gets the value of the teamID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTeamID() {
        return teamID;
    }

    /**
     * Sets the value of the teamID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTeamID(BigInteger value) {
        this.teamID = value;
    }

    /**
     * Gets the value of the teamName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * Sets the value of the teamName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamName(String value) {
        this.teamName = value;
    }

    /**
     * Gets the value of the shortTeamName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortTeamName() {
        return shortTeamName;
    }

    /**
     * Sets the value of the shortTeamName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortTeamName(String value) {
        this.shortTeamName = value;
    }

    /**
     * Gets the value of the arena property.
     * 
     * @return
     *     possible object is
     *     {@link Arena }
     *     
     */
    public Arena getArena() {
        return arena;
    }

    /**
     * Sets the value of the arena property.
     * 
     * @param value
     *     allowed object is
     *     {@link Arena }
     *     
     */
    public void setArena(Arena value) {
        this.arena = value;
    }

    /**
     * Gets the value of the league property.
     * 
     * @return
     *     possible object is
     *     {@link League }
     *     
     */
    public League getLeague() {
        return league;
    }

    /**
     * Sets the value of the league property.
     * 
     * @param value
     *     allowed object is
     *     {@link League }
     *     
     */
    public void setLeague(League value) {
        this.league = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link Region }
     *     
     */
    public Region getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link Region }
     *     
     */
    public void setRegion(Region value) {
        this.region = value;
    }

    /**
     * Gets the value of the trainer property.
     * 
     * @return
     *     possible object is
     *     {@link Trainer }
     *     
     */
    public Trainer getTrainer() {
        return trainer;
    }

    /**
     * Sets the value of the trainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trainer }
     *     
     */
    public void setTrainer(Trainer value) {
        this.trainer = value;
    }

    /**
     * Gets the value of the homePage property.
     * 
     * @return
     *     possible object is
     *     {@link HomePage }
     *     
     */
    public HomePage getHomePage() {
        return homePage;
    }

    /**
     * Sets the value of the homePage property.
     * 
     * @param value
     *     allowed object is
     *     {@link HomePage }
     *     
     */
    public void setHomePage(HomePage value) {
        this.homePage = value;
    }

    /**
     * Gets the value of the dressURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDressURI() {
        return dressURI;
    }

    /**
     * Sets the value of the dressURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDressURI(String value) {
        this.dressURI = value;
    }

    /**
     * Gets the value of the dressAlternateURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDressAlternateURI() {
        return dressAlternateURI;
    }

    /**
     * Sets the value of the dressAlternateURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDressAlternateURI(String value) {
        this.dressAlternateURI = value;
    }

    /**
     * Gets the value of the leagueLevelUnit property.
     * 
     * @return
     *     possible object is
     *     {@link LeagueLevelUnit }
     *     
     */
    public LeagueLevelUnit getLeagueLevelUnit() {
        return leagueLevelUnit;
    }

    /**
     * Sets the value of the leagueLevelUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeagueLevelUnit }
     *     
     */
    public void setLeagueLevelUnit(LeagueLevelUnit value) {
        this.leagueLevelUnit = value;
    }

    /**
     * Gets the value of the botStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BotStatus }
     *     
     */
    public BotStatus getBotStatus() {
        return botStatus;
    }

    /**
     * Sets the value of the botStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BotStatus }
     *     
     */
    public void setBotStatus(BotStatus value) {
        this.botStatus = value;
    }

    /**
     * Gets the value of the cup property.
     * 
     * @return
     *     possible object is
     *     {@link Cup }
     *     
     */
    public Cup getCup() {
        return cup;
    }

    /**
     * Sets the value of the cup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cup }
     *     
     */
    public void setCup(Cup value) {
        this.cup = value;
    }

    /**
     * Gets the value of the friendlyTeamID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFriendlyTeamID() {
        return friendlyTeamID;
    }

    /**
     * Sets the value of the friendlyTeamID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFriendlyTeamID(BigInteger value) {
        this.friendlyTeamID = value;
    }

    /**
     * Gets the value of the numberOfVictories property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfVictories() {
        return numberOfVictories;
    }

    /**
     * Sets the value of the numberOfVictories property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfVictories(BigInteger value) {
        this.numberOfVictories = value;
    }

    /**
     * Gets the value of the numberOfUndefeated property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfUndefeated() {
        return numberOfUndefeated;
    }

    /**
     * Sets the value of the numberOfUndefeated property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfUndefeated(BigInteger value) {
        this.numberOfUndefeated = value;
    }

    /**
     * Gets the value of the teamRank property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTeamRank() {
        return teamRank;
    }

    /**
     * Sets the value of the teamRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTeamRank(BigInteger value) {
        this.teamRank = value;
    }

    /**
     * Gets the value of the logoURL property.
     * 
     * @return
     *     possible object is
     *     {@link LogoURL }
     *     
     */
    public LogoURL getLogoURL() {
        return logoURL;
    }

    /**
     * Sets the value of the logoURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogoURL }
     *     
     */
    public void setLogoURL(LogoURL value) {
        this.logoURL = value;
    }

    /**
     * Gets the value of the fanclub property.
     * 
     * @return
     *     possible object is
     *     {@link Fanclub }
     *     
     */
    public Fanclub getFanclub() {
        return fanclub;
    }

    /**
     * Sets the value of the fanclub property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fanclub }
     *     
     */
    public void setFanclub(Fanclub value) {
        this.fanclub = value;
    }

    /**
     * Gets the value of the guestbook property.
     * 
     * @return
     *     possible object is
     *     {@link Guestbook }
     *     
     */
    public Guestbook getGuestbook() {
        return guestbook;
    }

    /**
     * Sets the value of the guestbook property.
     * 
     * @param value
     *     allowed object is
     *     {@link Guestbook }
     *     
     */
    public void setGuestbook(Guestbook value) {
        this.guestbook = value;
    }

    /**
     * Gets the value of the pressAnnouncement property.
     * 
     * @return
     *     possible object is
     *     {@link PressAnnouncement }
     *     
     */
    public PressAnnouncement getPressAnnouncement() {
        return pressAnnouncement;
    }

    /**
     * Sets the value of the pressAnnouncement property.
     * 
     * @param value
     *     allowed object is
     *     {@link PressAnnouncement }
     *     
     */
    public void setPressAnnouncement(PressAnnouncement value) {
        this.pressAnnouncement = value;
    }

    /**
     * Gets the value of the youthTeamID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getYouthTeamID() {
        return youthTeamID;
    }

    /**
     * Sets the value of the youthTeamID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setYouthTeamID(BigInteger value) {
        this.youthTeamID = value;
    }

    /**
     * Gets the value of the youthTeamName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYouthTeamName() {
        return youthTeamName;
    }

    /**
     * Sets the value of the youthTeamName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYouthTeamName(String value) {
        this.youthTeamName = value;
    }

    /**
     * Gets the value of the numberOfVisits property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfVisits() {
        return numberOfVisits;
    }

    /**
     * Sets the value of the numberOfVisits property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfVisits(BigInteger value) {
        this.numberOfVisits = value;
    }

    /**
     * Gets the value of the flags property.
     * 
     * @return
     *     possible object is
     *     {@link Flags }
     *     
     */
    public Flags getFlags() {
        return flags;
    }

    /**
     * Sets the value of the flags property.
     * 
     * @param value
     *     allowed object is
     *     {@link Flags }
     *     
     */
    public void setFlags(Flags value) {
        this.flags = value;
    }

}
