//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:50:09 AM CEST 
//


package models.training;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TrainingLevel_QNAME = new QName("", "TrainingLevel");
    private final static QName _FetchedDate_QNAME = new QName("", "FetchedDate");
    private final static QName _Experience352_QNAME = new QName("", "Experience352");
    private final static QName _TrainerName_QNAME = new QName("", "TrainerName");
    private final static QName _StaminaTrainingPart_QNAME = new QName("", "StaminaTrainingPart");
    private final static QName _UserID_QNAME = new QName("", "UserID");
    private final static QName _Experience343_QNAME = new QName("", "Experience343");
    private final static QName _Experience541_QNAME = new QName("", "Experience541");
    private final static QName _UserIsSupporter_QNAME = new QName("", "UserIsSupporter");
    private final static QName _Experience532_QNAME = new QName("", "Experience532");
    private final static QName _Experience433_QNAME = new QName("", "Experience433");
    private final static QName _TrainingType_QNAME = new QName("", "TrainingType");
    private final static QName _UserHasClubHouse_QNAME = new QName("", "UserHasClubHouse");
    private final static QName _TeamName_QNAME = new QName("", "TeamName");
    private final static QName _ArrivalDate_QNAME = new QName("", "ArrivalDate");
    private final static QName _TeamID_QNAME = new QName("", "TeamID");
    private final static QName _FileName_QNAME = new QName("", "FileName");
    private final static QName _TrainerID_QNAME = new QName("", "TrainerID");
    private final static QName _Version_QNAME = new QName("", "Version");
    private final static QName _Experience451_QNAME = new QName("", "Experience451");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NewTrainingLevel }
     * 
     */
    public NewTrainingLevel createNewTrainingLevel() {
        return new NewTrainingLevel();
    }

    /**
     * Create an instance of {@link SelfConfidence }
     * 
     */
    public SelfConfidence createSelfConfidence() {
        return new SelfConfidence();
    }

    /**
     * Create an instance of {@link Trainer }
     * 
     */
    public Trainer createTrainer() {
        return new Trainer();
    }

    /**
     * Create an instance of {@link HattrickData }
     * 
     */
    public HattrickData createHattrickData() {
        return new HattrickData();
    }

    /**
     * Create an instance of {@link Team }
     * 
     */
    public Team createTeam() {
        return new Team();
    }

    /**
     * Create an instance of {@link Morale }
     * 
     */
    public Morale createMorale() {
        return new Morale();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrainingLevel")
    public JAXBElement<BigInteger> createTrainingLevel(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrainingLevel_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FetchedDate")
    public JAXBElement<String> createFetchedDate(String value) {
        return new JAXBElement<String>(_FetchedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Experience352")
    public JAXBElement<BigInteger> createExperience352(BigInteger value) {
        return new JAXBElement<BigInteger>(_Experience352_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrainerName")
    public JAXBElement<String> createTrainerName(String value) {
        return new JAXBElement<String>(_TrainerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StaminaTrainingPart")
    public JAXBElement<BigInteger> createStaminaTrainingPart(BigInteger value) {
        return new JAXBElement<BigInteger>(_StaminaTrainingPart_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserID")
    public JAXBElement<BigInteger> createUserID(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Experience343")
    public JAXBElement<BigInteger> createExperience343(BigInteger value) {
        return new JAXBElement<BigInteger>(_Experience343_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Experience541")
    public JAXBElement<BigInteger> createExperience541(BigInteger value) {
        return new JAXBElement<BigInteger>(_Experience541_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserIsSupporter")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUserIsSupporter(String value) {
        return new JAXBElement<String>(_UserIsSupporter_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Experience532")
    public JAXBElement<BigInteger> createExperience532(BigInteger value) {
        return new JAXBElement<BigInteger>(_Experience532_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Experience433")
    public JAXBElement<BigInteger> createExperience433(BigInteger value) {
        return new JAXBElement<BigInteger>(_Experience433_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrainingType")
    public JAXBElement<BigInteger> createTrainingType(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrainingType_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserHasClubHouse")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUserHasClubHouse(String value) {
        return new JAXBElement<String>(_UserHasClubHouse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TeamName")
    public JAXBElement<String> createTeamName(String value) {
        return new JAXBElement<String>(_TeamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArrivalDate")
    public JAXBElement<String> createArrivalDate(String value) {
        return new JAXBElement<String>(_ArrivalDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TeamID")
    public JAXBElement<BigInteger> createTeamID(BigInteger value) {
        return new JAXBElement<BigInteger>(_TeamID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FileName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFileName(String value) {
        return new JAXBElement<String>(_FileName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrainerID")
    public JAXBElement<BigInteger> createTrainerID(BigInteger value) {
        return new JAXBElement<BigInteger>(_TrainerID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Version")
    public JAXBElement<BigDecimal> createVersion(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Version_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Experience451")
    public JAXBElement<BigInteger> createExperience451(BigInteger value) {
        return new JAXBElement<BigInteger>(_Experience451_QNAME, BigInteger.class, null, value);
    }

}
