//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:47:20 AM CEST 
//


package models.playerdetails;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PlayerID"/>
 *         &lt;element ref="{}PlayerName"/>
 *         &lt;element ref="{}PlayerNumber"/>
 *         &lt;element ref="{}Age"/>
 *         &lt;element ref="{}AgeDays"/>
 *         &lt;element ref="{}PlayerForm"/>
 *         &lt;element ref="{}Cards"/>
 *         &lt;element ref="{}InjuryLevel"/>
 *         &lt;element ref="{}Statement"/>
 *         &lt;element ref="{}PlayerLanguage"/>
 *         &lt;element ref="{}TrainerData"/>
 *         &lt;element ref="{}OwningTeam"/>
 *         &lt;element ref="{}Salary"/>
 *         &lt;element ref="{}IsAbroad"/>
 *         &lt;element ref="{}Agreeability"/>
 *         &lt;element ref="{}Aggressiveness"/>
 *         &lt;element ref="{}Honesty"/>
 *         &lt;element ref="{}Experience"/>
 *         &lt;element ref="{}Leadership"/>
 *         &lt;element ref="{}Specialty"/>
 *         &lt;element ref="{}NativeLeagueID"/>
 *         &lt;element ref="{}NativeLeagueName"/>
 *         &lt;element ref="{}TSI"/>
 *         &lt;element ref="{}PlayerSkills"/>
 *         &lt;element ref="{}Caps"/>
 *         &lt;element ref="{}CapsU20"/>
 *         &lt;element ref="{}CareerGoals"/>
 *         &lt;element ref="{}CareerHattricks"/>
 *         &lt;element ref="{}LeagueGoals"/>
 *         &lt;element ref="{}CupGoals"/>
 *         &lt;element ref="{}TransferListed"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "playerID",
    "playerName",
    "playerNumber",
    "age",
    "ageDays",
    "playerForm",
    "cards",
    "injuryLevel",
    "statement",
    "playerLanguage",
    "trainerData",
    "owningTeam",
    "salary",
    "isAbroad",
    "agreeability",
    "aggressiveness",
    "honesty",
    "experience",
    "leadership",
    "specialty",
    "nativeLeagueID",
    "nativeLeagueName",
    "tsi",
    "playerSkills",
    "caps",
    "capsU20",
    "careerGoals",
    "careerHattricks",
    "leagueGoals",
    "cupGoals",
    "transferListed"
})
@XmlRootElement(name = "Player")
public class Player {

    @XmlElement(name = "PlayerID", required = true)
    protected BigInteger playerID;
    @XmlElement(name = "PlayerName", required = true)
    protected String playerName;
    @XmlElement(name = "PlayerNumber", required = true)
    protected BigInteger playerNumber;
    @XmlElement(name = "Age", required = true)
    protected BigInteger age;
    @XmlElement(name = "AgeDays", required = true)
    protected BigInteger ageDays;
    @XmlElement(name = "PlayerForm", required = true)
    protected BigInteger playerForm;
    @XmlElement(name = "Cards", required = true)
    protected BigInteger cards;
    @XmlElement(name = "InjuryLevel", required = true)
    protected BigInteger injuryLevel;
    @XmlElement(name = "Statement", required = true)
    protected Statement statement;
    @XmlElement(name = "PlayerLanguage", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String playerLanguage;
    @XmlElement(name = "TrainerData", required = true)
    protected TrainerData trainerData;
    @XmlElement(name = "OwningTeam", required = true)
    protected OwningTeam owningTeam;
    @XmlElement(name = "Salary", required = true)
    protected BigInteger salary;
    @XmlElement(name = "IsAbroad", required = true)
    protected BigInteger isAbroad;
    @XmlElement(name = "Agreeability", required = true)
    protected BigInteger agreeability;
    @XmlElement(name = "Aggressiveness", required = true)
    protected BigInteger aggressiveness;
    @XmlElement(name = "Honesty", required = true)
    protected BigInteger honesty;
    @XmlElement(name = "Experience", required = true)
    protected BigInteger experience;
    @XmlElement(name = "Leadership", required = true)
    protected BigInteger leadership;
    @XmlElement(name = "Specialty", required = true)
    protected BigInteger specialty;
    @XmlElement(name = "NativeLeagueID", required = true)
    protected BigInteger nativeLeagueID;
    @XmlElement(name = "NativeLeagueName", required = true)
    protected String nativeLeagueName;
    @XmlElement(name = "TSI", required = true)
    protected BigInteger tsi;
    @XmlElement(name = "PlayerSkills", required = true)
    protected PlayerSkills playerSkills;
    @XmlElement(name = "Caps", required = true)
    protected BigInteger caps;
    @XmlElement(name = "CapsU20", required = true)
    protected BigInteger capsU20;
    @XmlElement(name = "CareerGoals", required = true)
    protected BigInteger careerGoals;
    @XmlElement(name = "CareerHattricks", required = true)
    protected BigInteger careerHattricks;
    @XmlElement(name = "LeagueGoals", required = true)
    protected BigInteger leagueGoals;
    @XmlElement(name = "CupGoals", required = true)
    protected BigInteger cupGoals;
    @XmlElement(name = "TransferListed", required = true)
    protected BigInteger transferListed;

    /**
     * Gets the value of the playerID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlayerID() {
        return playerID;
    }

    /**
     * Sets the value of the playerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlayerID(BigInteger value) {
        this.playerID = value;
    }

    /**
     * Gets the value of the playerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * Sets the value of the playerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayerName(String value) {
        this.playerName = value;
    }

    /**
     * Gets the value of the playerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlayerNumber() {
        return playerNumber;
    }

    /**
     * Sets the value of the playerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlayerNumber(BigInteger value) {
        this.playerNumber = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAge(BigInteger value) {
        this.age = value;
    }

    /**
     * Gets the value of the ageDays property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgeDays() {
        return ageDays;
    }

    /**
     * Sets the value of the ageDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgeDays(BigInteger value) {
        this.ageDays = value;
    }

    /**
     * Gets the value of the playerForm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlayerForm() {
        return playerForm;
    }

    /**
     * Sets the value of the playerForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlayerForm(BigInteger value) {
        this.playerForm = value;
    }

    /**
     * Gets the value of the cards property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCards() {
        return cards;
    }

    /**
     * Sets the value of the cards property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCards(BigInteger value) {
        this.cards = value;
    }

    /**
     * Gets the value of the injuryLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInjuryLevel() {
        return injuryLevel;
    }

    /**
     * Sets the value of the injuryLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInjuryLevel(BigInteger value) {
        this.injuryLevel = value;
    }

    /**
     * Gets the value of the statement property.
     * 
     * @return
     *     possible object is
     *     {@link Statement }
     *     
     */
    public Statement getStatement() {
        return statement;
    }

    /**
     * Sets the value of the statement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statement }
     *     
     */
    public void setStatement(Statement value) {
        this.statement = value;
    }

    /**
     * Gets the value of the playerLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayerLanguage() {
        return playerLanguage;
    }

    /**
     * Sets the value of the playerLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayerLanguage(String value) {
        this.playerLanguage = value;
    }

    /**
     * Gets the value of the trainerData property.
     * 
     * @return
     *     possible object is
     *     {@link TrainerData }
     *     
     */
    public TrainerData getTrainerData() {
        return trainerData;
    }

    /**
     * Sets the value of the trainerData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainerData }
     *     
     */
    public void setTrainerData(TrainerData value) {
        this.trainerData = value;
    }

    /**
     * Gets the value of the owningTeam property.
     * 
     * @return
     *     possible object is
     *     {@link OwningTeam }
     *     
     */
    public OwningTeam getOwningTeam() {
        return owningTeam;
    }

    /**
     * Sets the value of the owningTeam property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwningTeam }
     *     
     */
    public void setOwningTeam(OwningTeam value) {
        this.owningTeam = value;
    }

    /**
     * Gets the value of the salary property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSalary() {
        return salary;
    }

    /**
     * Sets the value of the salary property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSalary(BigInteger value) {
        this.salary = value;
    }

    /**
     * Gets the value of the isAbroad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsAbroad() {
        return isAbroad;
    }

    /**
     * Sets the value of the isAbroad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsAbroad(BigInteger value) {
        this.isAbroad = value;
    }

    /**
     * Gets the value of the agreeability property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgreeability() {
        return agreeability;
    }

    /**
     * Sets the value of the agreeability property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgreeability(BigInteger value) {
        this.agreeability = value;
    }

    /**
     * Gets the value of the aggressiveness property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAggressiveness() {
        return aggressiveness;
    }

    /**
     * Sets the value of the aggressiveness property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAggressiveness(BigInteger value) {
        this.aggressiveness = value;
    }

    /**
     * Gets the value of the honesty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHonesty() {
        return honesty;
    }

    /**
     * Sets the value of the honesty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHonesty(BigInteger value) {
        this.honesty = value;
    }

    /**
     * Gets the value of the experience property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExperience() {
        return experience;
    }

    /**
     * Sets the value of the experience property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExperience(BigInteger value) {
        this.experience = value;
    }

    /**
     * Gets the value of the leadership property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLeadership() {
        return leadership;
    }

    /**
     * Sets the value of the leadership property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLeadership(BigInteger value) {
        this.leadership = value;
    }

    /**
     * Gets the value of the specialty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSpecialty() {
        return specialty;
    }

    /**
     * Sets the value of the specialty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSpecialty(BigInteger value) {
        this.specialty = value;
    }

    /**
     * Gets the value of the nativeLeagueID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNativeLeagueID() {
        return nativeLeagueID;
    }

    /**
     * Sets the value of the nativeLeagueID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNativeLeagueID(BigInteger value) {
        this.nativeLeagueID = value;
    }

    /**
     * Gets the value of the nativeLeagueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNativeLeagueName() {
        return nativeLeagueName;
    }

    /**
     * Sets the value of the nativeLeagueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNativeLeagueName(String value) {
        this.nativeLeagueName = value;
    }

    /**
     * Gets the value of the tsi property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTSI() {
        return tsi;
    }

    /**
     * Sets the value of the tsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTSI(BigInteger value) {
        this.tsi = value;
    }

    /**
     * Gets the value of the playerSkills property.
     * 
     * @return
     *     possible object is
     *     {@link PlayerSkills }
     *     
     */
    public PlayerSkills getPlayerSkills() {
        return playerSkills;
    }

    /**
     * Sets the value of the playerSkills property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayerSkills }
     *     
     */
    public void setPlayerSkills(PlayerSkills value) {
        this.playerSkills = value;
    }

    /**
     * Gets the value of the caps property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCaps() {
        return caps;
    }

    /**
     * Sets the value of the caps property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCaps(BigInteger value) {
        this.caps = value;
    }

    /**
     * Gets the value of the capsU20 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCapsU20() {
        return capsU20;
    }

    /**
     * Sets the value of the capsU20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCapsU20(BigInteger value) {
        this.capsU20 = value;
    }

    /**
     * Gets the value of the careerGoals property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCareerGoals() {
        return careerGoals;
    }

    /**
     * Sets the value of the careerGoals property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCareerGoals(BigInteger value) {
        this.careerGoals = value;
    }

    /**
     * Gets the value of the careerHattricks property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCareerHattricks() {
        return careerHattricks;
    }

    /**
     * Sets the value of the careerHattricks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCareerHattricks(BigInteger value) {
        this.careerHattricks = value;
    }

    /**
     * Gets the value of the leagueGoals property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLeagueGoals() {
        return leagueGoals;
    }

    /**
     * Sets the value of the leagueGoals property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLeagueGoals(BigInteger value) {
        this.leagueGoals = value;
    }

    /**
     * Gets the value of the cupGoals property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCupGoals() {
        return cupGoals;
    }

    /**
     * Sets the value of the cupGoals property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCupGoals(BigInteger value) {
        this.cupGoals = value;
    }

    /**
     * Gets the value of the transferListed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTransferListed() {
        return transferListed;
    }

    /**
     * Sets the value of the transferListed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTransferListed(BigInteger value) {
        this.transferListed = value;
    }

}
