//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:48:19 AM CEST 
//


package models.players;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PlayerID"/>
 *         &lt;element ref="{}PlayerName"/>
 *         &lt;element ref="{}PlayerNumber"/>
 *         &lt;element ref="{}Age"/>
 *         &lt;element ref="{}AgeDays"/>
 *         &lt;element ref="{}TSI"/>
 *         &lt;element ref="{}PlayerForm"/>
 *         &lt;element ref="{}Statement"/>
 *         &lt;element ref="{}Experience"/>
 *         &lt;element ref="{}Leadership"/>
 *         &lt;element ref="{}Salary"/>
 *         &lt;element ref="{}IsAbroad"/>
 *         &lt;element ref="{}Agreeability"/>
 *         &lt;element ref="{}Aggressiveness"/>
 *         &lt;element ref="{}Honesty"/>
 *         &lt;element ref="{}LeagueGoals"/>
 *         &lt;element ref="{}CupGoals"/>
 *         &lt;element ref="{}FriendliesGoals"/>
 *         &lt;element ref="{}CareerGoals"/>
 *         &lt;element ref="{}CareerHattricks"/>
 *         &lt;element ref="{}Specialty"/>
 *         &lt;element ref="{}TransferListed"/>
 *         &lt;element ref="{}NationalTeamID"/>
 *         &lt;element ref="{}CountryID"/>
 *         &lt;element ref="{}Caps"/>
 *         &lt;element ref="{}CapsU20"/>
 *         &lt;element ref="{}Cards"/>
 *         &lt;element ref="{}InjuryLevel"/>
 *         &lt;element ref="{}StaminaSkill"/>
 *         &lt;element ref="{}KeeperSkill"/>
 *         &lt;element ref="{}PlaymakerSkill"/>
 *         &lt;element ref="{}ScorerSkill"/>
 *         &lt;element ref="{}PassingSkill"/>
 *         &lt;element ref="{}WingerSkill"/>
 *         &lt;element ref="{}DefenderSkill"/>
 *         &lt;element ref="{}SetPiecesSkill"/>
 *         &lt;element ref="{}PlayerCategoryId"/>
 *         &lt;element ref="{}TrainerData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "playerID",
    "playerName",
    "playerNumber",
    "age",
    "ageDays",
    "tsi",
    "playerForm",
    "statement",
    "experience",
    "leadership",
    "salary",
    "isAbroad",
    "agreeability",
    "aggressiveness",
    "honesty",
    "leagueGoals",
    "cupGoals",
    "friendliesGoals",
    "careerGoals",
    "careerHattricks",
    "specialty",
    "transferListed",
    "nationalTeamID",
    "countryID",
    "caps",
    "capsU20",
    "cards",
    "injuryLevel",
    "staminaSkill",
    "keeperSkill",
    "playmakerSkill",
    "scorerSkill",
    "passingSkill",
    "wingerSkill",
    "defenderSkill",
    "setPiecesSkill",
    "playerCategoryId",
    "trainerData"
})
@XmlRootElement(name = "Player")
public class Player {

    @XmlElement(name = "PlayerID", required = true)
    protected BigInteger playerID;
    @XmlElement(name = "PlayerName", required = true)
    protected String playerName;
    @XmlElement(name = "PlayerNumber", required = true)
    protected BigInteger playerNumber;
    @XmlElement(name = "Age", required = true)
    protected BigInteger age;
    @XmlElement(name = "AgeDays", required = true)
    protected BigInteger ageDays;
    @XmlElement(name = "TSI", required = true)
    protected BigInteger tsi;
    @XmlElement(name = "PlayerForm", required = true)
    protected BigInteger playerForm;
    @XmlElement(name = "Statement", required = true)
    protected Statement statement;
    @XmlElement(name = "Experience", required = true)
    protected BigInteger experience;
    @XmlElement(name = "Leadership", required = true)
    protected BigInteger leadership;
    @XmlElement(name = "Salary", required = true)
    protected BigInteger salary;
    @XmlElement(name = "IsAbroad", required = true)
    protected BigInteger isAbroad;
    @XmlElement(name = "Agreeability", required = true)
    protected BigInteger agreeability;
    @XmlElement(name = "Aggressiveness", required = true)
    protected BigInteger aggressiveness;
    @XmlElement(name = "Honesty", required = true)
    protected BigInteger honesty;
    @XmlElement(name = "LeagueGoals", required = true)
    protected BigInteger leagueGoals;
    @XmlElement(name = "CupGoals", required = true)
    protected BigInteger cupGoals;
    @XmlElement(name = "FriendliesGoals", required = true)
    protected BigInteger friendliesGoals;
    @XmlElement(name = "CareerGoals", required = true)
    protected BigInteger careerGoals;
    @XmlElement(name = "CareerHattricks", required = true)
    protected BigInteger careerHattricks;
    @XmlElement(name = "Specialty", required = true)
    protected BigInteger specialty;
    @XmlElement(name = "TransferListed", required = true)
    protected BigInteger transferListed;
    @XmlElement(name = "NationalTeamID", required = true)
    protected BigInteger nationalTeamID;
    @XmlElement(name = "CountryID", required = true)
    protected BigInteger countryID;
    @XmlElement(name = "Caps", required = true)
    protected BigInteger caps;
    @XmlElement(name = "CapsU20", required = true)
    protected BigInteger capsU20;
    @XmlElement(name = "Cards", required = true)
    protected BigInteger cards;
    @XmlElement(name = "InjuryLevel", required = true)
    protected BigInteger injuryLevel;
    @XmlElement(name = "StaminaSkill", required = true)
    protected BigInteger staminaSkill;
    @XmlElement(name = "KeeperSkill", required = true)
    protected BigInteger keeperSkill;
    @XmlElement(name = "PlaymakerSkill", required = true)
    protected BigInteger playmakerSkill;
    @XmlElement(name = "ScorerSkill", required = true)
    protected BigInteger scorerSkill;
    @XmlElement(name = "PassingSkill", required = true)
    protected BigInteger passingSkill;
    @XmlElement(name = "WingerSkill", required = true)
    protected BigInteger wingerSkill;
    @XmlElement(name = "DefenderSkill", required = true)
    protected BigInteger defenderSkill;
    @XmlElement(name = "SetPiecesSkill", required = true)
    protected BigInteger setPiecesSkill;
    @XmlElement(name = "PlayerCategoryId", required = true)
    protected BigInteger playerCategoryId;
    @XmlElement(name = "TrainerData")
    protected TrainerData trainerData;

    /**
     * Gets the value of the playerID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlayerID() {
        return playerID;
    }

    /**
     * Sets the value of the playerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlayerID(BigInteger value) {
        this.playerID = value;
    }

    /**
     * Gets the value of the playerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * Sets the value of the playerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayerName(String value) {
        this.playerName = value;
    }

    /**
     * Gets the value of the playerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlayerNumber() {
        return playerNumber;
    }

    /**
     * Sets the value of the playerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlayerNumber(BigInteger value) {
        this.playerNumber = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAge(BigInteger value) {
        this.age = value;
    }

    /**
     * Gets the value of the ageDays property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgeDays() {
        return ageDays;
    }

    /**
     * Sets the value of the ageDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgeDays(BigInteger value) {
        this.ageDays = value;
    }

    /**
     * Gets the value of the tsi property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTSI() {
        return tsi;
    }

    /**
     * Sets the value of the tsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTSI(BigInteger value) {
        this.tsi = value;
    }

    /**
     * Gets the value of the playerForm property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlayerForm() {
        return playerForm;
    }

    /**
     * Sets the value of the playerForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlayerForm(BigInteger value) {
        this.playerForm = value;
    }

    /**
     * Gets the value of the statement property.
     * 
     * @return
     *     possible object is
     *     {@link Statement }
     *     
     */
    public Statement getStatement() {
        return statement;
    }

    /**
     * Sets the value of the statement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Statement }
     *     
     */
    public void setStatement(Statement value) {
        this.statement = value;
    }

    /**
     * Gets the value of the experience property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExperience() {
        return experience;
    }

    /**
     * Sets the value of the experience property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExperience(BigInteger value) {
        this.experience = value;
    }

    /**
     * Gets the value of the leadership property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLeadership() {
        return leadership;
    }

    /**
     * Sets the value of the leadership property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLeadership(BigInteger value) {
        this.leadership = value;
    }

    /**
     * Gets the value of the salary property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSalary() {
        return salary;
    }

    /**
     * Sets the value of the salary property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSalary(BigInteger value) {
        this.salary = value;
    }

    /**
     * Gets the value of the isAbroad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIsAbroad() {
        return isAbroad;
    }

    /**
     * Sets the value of the isAbroad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIsAbroad(BigInteger value) {
        this.isAbroad = value;
    }

    /**
     * Gets the value of the agreeability property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgreeability() {
        return agreeability;
    }

    /**
     * Sets the value of the agreeability property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgreeability(BigInteger value) {
        this.agreeability = value;
    }

    /**
     * Gets the value of the aggressiveness property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAggressiveness() {
        return aggressiveness;
    }

    /**
     * Sets the value of the aggressiveness property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAggressiveness(BigInteger value) {
        this.aggressiveness = value;
    }

    /**
     * Gets the value of the honesty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHonesty() {
        return honesty;
    }

    /**
     * Sets the value of the honesty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHonesty(BigInteger value) {
        this.honesty = value;
    }

    /**
     * Gets the value of the leagueGoals property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLeagueGoals() {
        return leagueGoals;
    }

    /**
     * Sets the value of the leagueGoals property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLeagueGoals(BigInteger value) {
        this.leagueGoals = value;
    }

    /**
     * Gets the value of the cupGoals property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCupGoals() {
        return cupGoals;
    }

    /**
     * Sets the value of the cupGoals property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCupGoals(BigInteger value) {
        this.cupGoals = value;
    }

    /**
     * Gets the value of the friendliesGoals property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFriendliesGoals() {
        return friendliesGoals;
    }

    /**
     * Sets the value of the friendliesGoals property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFriendliesGoals(BigInteger value) {
        this.friendliesGoals = value;
    }

    /**
     * Gets the value of the careerGoals property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCareerGoals() {
        return careerGoals;
    }

    /**
     * Sets the value of the careerGoals property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCareerGoals(BigInteger value) {
        this.careerGoals = value;
    }

    /**
     * Gets the value of the careerHattricks property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCareerHattricks() {
        return careerHattricks;
    }

    /**
     * Sets the value of the careerHattricks property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCareerHattricks(BigInteger value) {
        this.careerHattricks = value;
    }

    /**
     * Gets the value of the specialty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSpecialty() {
        return specialty;
    }

    /**
     * Sets the value of the specialty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSpecialty(BigInteger value) {
        this.specialty = value;
    }

    /**
     * Gets the value of the transferListed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTransferListed() {
        return transferListed;
    }

    /**
     * Sets the value of the transferListed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTransferListed(BigInteger value) {
        this.transferListed = value;
    }

    /**
     * Gets the value of the nationalTeamID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNationalTeamID() {
        return nationalTeamID;
    }

    /**
     * Sets the value of the nationalTeamID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNationalTeamID(BigInteger value) {
        this.nationalTeamID = value;
    }

    /**
     * Gets the value of the countryID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCountryID() {
        return countryID;
    }

    /**
     * Sets the value of the countryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCountryID(BigInteger value) {
        this.countryID = value;
    }

    /**
     * Gets the value of the caps property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCaps() {
        return caps;
    }

    /**
     * Sets the value of the caps property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCaps(BigInteger value) {
        this.caps = value;
    }

    /**
     * Gets the value of the capsU20 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCapsU20() {
        return capsU20;
    }

    /**
     * Sets the value of the capsU20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCapsU20(BigInteger value) {
        this.capsU20 = value;
    }

    /**
     * Gets the value of the cards property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCards() {
        return cards;
    }

    /**
     * Sets the value of the cards property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCards(BigInteger value) {
        this.cards = value;
    }

    /**
     * Gets the value of the injuryLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInjuryLevel() {
        return injuryLevel;
    }

    /**
     * Sets the value of the injuryLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInjuryLevel(BigInteger value) {
        this.injuryLevel = value;
    }

    /**
     * Gets the value of the staminaSkill property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStaminaSkill() {
        return staminaSkill;
    }

    /**
     * Sets the value of the staminaSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStaminaSkill(BigInteger value) {
        this.staminaSkill = value;
    }

    /**
     * Gets the value of the keeperSkill property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKeeperSkill() {
        return keeperSkill;
    }

    /**
     * Sets the value of the keeperSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKeeperSkill(BigInteger value) {
        this.keeperSkill = value;
    }

    /**
     * Gets the value of the playmakerSkill property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlaymakerSkill() {
        return playmakerSkill;
    }

    /**
     * Sets the value of the playmakerSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlaymakerSkill(BigInteger value) {
        this.playmakerSkill = value;
    }

    /**
     * Gets the value of the scorerSkill property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getScorerSkill() {
        return scorerSkill;
    }

    /**
     * Sets the value of the scorerSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setScorerSkill(BigInteger value) {
        this.scorerSkill = value;
    }

    /**
     * Gets the value of the passingSkill property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPassingSkill() {
        return passingSkill;
    }

    /**
     * Sets the value of the passingSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPassingSkill(BigInteger value) {
        this.passingSkill = value;
    }

    /**
     * Gets the value of the wingerSkill property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWingerSkill() {
        return wingerSkill;
    }

    /**
     * Sets the value of the wingerSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWingerSkill(BigInteger value) {
        this.wingerSkill = value;
    }

    /**
     * Gets the value of the defenderSkill property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDefenderSkill() {
        return defenderSkill;
    }

    /**
     * Sets the value of the defenderSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDefenderSkill(BigInteger value) {
        this.defenderSkill = value;
    }

    /**
     * Gets the value of the setPiecesSkill property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSetPiecesSkill() {
        return setPiecesSkill;
    }

    /**
     * Sets the value of the setPiecesSkill property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSetPiecesSkill(BigInteger value) {
        this.setPiecesSkill = value;
    }

    /**
     * Gets the value of the playerCategoryId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlayerCategoryId() {
        return playerCategoryId;
    }

    /**
     * Sets the value of the playerCategoryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlayerCategoryId(BigInteger value) {
        this.playerCategoryId = value;
    }

    /**
     * Gets the value of the trainerData property.
     * 
     * @return
     *     possible object is
     *     {@link TrainerData }
     *     
     */
    public TrainerData getTrainerData() {
        return trainerData;
    }

    /**
     * Sets the value of the trainerData property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainerData }
     *     
     */
    public void setTrainerData(TrainerData value) {
        this.trainerData = value;
    }

}
