//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:44:15 AM CEST 
//


package models.matchdetails;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MatchType_QNAME = new QName("", "MatchType");
    private final static QName _FetchedDate_QNAME = new QName("", "FetchedDate");
    private final static QName _AwayGoals_QNAME = new QName("", "AwayGoals");
    private final static QName _IsYouth_QNAME = new QName("", "IsYouth");
    private final static QName _UserID_QNAME = new QName("", "UserID");
    private final static QName _Dress_QNAME = new QName("", "Dress");
    private final static QName _MatchDate_QNAME = new QName("", "MatchDate");
    private final static QName _HomeTeamName_QNAME = new QName("", "HomeTeamName");
    private final static QName _RatingRightDef_QNAME = new QName("", "RatingRightDef");
    private final static QName _WeatherID_QNAME = new QName("", "WeatherID");
    private final static QName _HomeGoals_QNAME = new QName("", "HomeGoals");
    private final static QName _PossessionFirstHalfHome_QNAME = new QName("", "PossessionFirstHalfHome");
    private final static QName _RatingMidDef_QNAME = new QName("", "RatingMidDef");
    private final static QName _ScorerPlayerID_QNAME = new QName("", "ScorerPlayerID");
    private final static QName _Version_QNAME = new QName("", "Version");
    private final static QName _ArenaID_QNAME = new QName("", "ArenaID");
    private final static QName _PossessionSecondHalfHome_QNAME = new QName("", "PossessionSecondHalfHome");
    private final static QName _SoldTotal_QNAME = new QName("", "SoldTotal");
    private final static QName _PossessionFirstHalfAway_QNAME = new QName("", "PossessionFirstHalfAway");
    private final static QName _TeamAttitude_QNAME = new QName("", "TeamAttitude");
    private final static QName _TacticType_QNAME = new QName("", "TacticType");
    private final static QName _AwayTeamID_QNAME = new QName("", "AwayTeamID");
    private final static QName _RatingLeftAtt_QNAME = new QName("", "RatingLeftAtt");
    private final static QName _PossessionSecondHalfAway_QNAME = new QName("", "PossessionSecondHalfAway");
    private final static QName _RatingMidAtt_QNAME = new QName("", "RatingMidAtt");
    private final static QName _RatingLeftDef_QNAME = new QName("", "RatingLeftDef");
    private final static QName _ScorerHomeGoals_QNAME = new QName("", "ScorerHomeGoals");
    private final static QName _ScorerTeamID_QNAME = new QName("", "ScorerTeamID");
    private final static QName _ScorerMinute_QNAME = new QName("", "ScorerMinute");
    private final static QName _TacticSkill_QNAME = new QName("", "TacticSkill");
    private final static QName _ArenaName_QNAME = new QName("", "ArenaName");
    private final static QName _UserIsSupporter_QNAME = new QName("", "UserIsSupporter");
    private final static QName _AwayTeamName_QNAME = new QName("", "AwayTeamName");
    private final static QName _RatingMidfield_QNAME = new QName("", "RatingMidfield");
    private final static QName _UserHasClubHouse_QNAME = new QName("", "UserHasClubHouse");
    private final static QName _ScorerPlayerName_QNAME = new QName("", "ScorerPlayerName");
    private final static QName _RatingRightAtt_QNAME = new QName("", "RatingRightAtt");
    private final static QName _ScorerAwayGoals_QNAME = new QName("", "ScorerAwayGoals");
    private final static QName _FileName_QNAME = new QName("", "FileName");
    private final static QName _FinishedDate_QNAME = new QName("", "FinishedDate");
    private final static QName _HomeTeamID_QNAME = new QName("", "HomeTeamID");
    private final static QName _MatchID_QNAME = new QName("", "MatchID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Arena }
     * 
     */
    public Arena createArena() {
        return new Arena();
    }

    /**
     * Create an instance of {@link Scorers }
     * 
     */
    public Scorers createScorers() {
        return new Scorers();
    }

    /**
     * Create an instance of {@link Goal }
     * 
     */
    public Goal createGoal() {
        return new Goal();
    }

    /**
     * Create an instance of {@link AwayTeam }
     * 
     */
    public AwayTeam createAwayTeam() {
        return new AwayTeam();
    }

    /**
     * Create an instance of {@link Bookings }
     * 
     */
    public Bookings createBookings() {
        return new Bookings();
    }

    /**
     * Create an instance of {@link Match }
     * 
     */
    public Match createMatch() {
        return new Match();
    }

    /**
     * Create an instance of {@link HattrickData }
     * 
     */
    public HattrickData createHattrickData() {
        return new HattrickData();
    }

    /**
     * Create an instance of {@link HomeTeam }
     * 
     */
    public HomeTeam createHomeTeam() {
        return new HomeTeam();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MatchType")
    public JAXBElement<BigInteger> createMatchType(BigInteger value) {
        return new JAXBElement<BigInteger>(_MatchType_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FetchedDate")
    public JAXBElement<String> createFetchedDate(String value) {
        return new JAXBElement<String>(_FetchedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AwayGoals")
    public JAXBElement<BigInteger> createAwayGoals(BigInteger value) {
        return new JAXBElement<BigInteger>(_AwayGoals_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsYouth")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createIsYouth(String value) {
        return new JAXBElement<String>(_IsYouth_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserID")
    public JAXBElement<BigInteger> createUserID(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Dress")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDress(String value) {
        return new JAXBElement<String>(_Dress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MatchDate")
    public JAXBElement<String> createMatchDate(String value) {
        return new JAXBElement<String>(_MatchDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HomeTeamName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createHomeTeamName(String value) {
        return new JAXBElement<String>(_HomeTeamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RatingRightDef")
    public JAXBElement<BigInteger> createRatingRightDef(BigInteger value) {
        return new JAXBElement<BigInteger>(_RatingRightDef_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WeatherID")
    public JAXBElement<BigInteger> createWeatherID(BigInteger value) {
        return new JAXBElement<BigInteger>(_WeatherID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HomeGoals")
    public JAXBElement<BigInteger> createHomeGoals(BigInteger value) {
        return new JAXBElement<BigInteger>(_HomeGoals_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PossessionFirstHalfHome")
    public JAXBElement<BigInteger> createPossessionFirstHalfHome(BigInteger value) {
        return new JAXBElement<BigInteger>(_PossessionFirstHalfHome_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RatingMidDef")
    public JAXBElement<BigInteger> createRatingMidDef(BigInteger value) {
        return new JAXBElement<BigInteger>(_RatingMidDef_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ScorerPlayerID")
    public JAXBElement<BigInteger> createScorerPlayerID(BigInteger value) {
        return new JAXBElement<BigInteger>(_ScorerPlayerID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Version")
    public JAXBElement<BigDecimal> createVersion(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Version_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArenaID")
    public JAXBElement<BigInteger> createArenaID(BigInteger value) {
        return new JAXBElement<BigInteger>(_ArenaID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PossessionSecondHalfHome")
    public JAXBElement<BigInteger> createPossessionSecondHalfHome(BigInteger value) {
        return new JAXBElement<BigInteger>(_PossessionSecondHalfHome_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SoldTotal")
    public JAXBElement<BigInteger> createSoldTotal(BigInteger value) {
        return new JAXBElement<BigInteger>(_SoldTotal_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PossessionFirstHalfAway")
    public JAXBElement<BigInteger> createPossessionFirstHalfAway(BigInteger value) {
        return new JAXBElement<BigInteger>(_PossessionFirstHalfAway_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TeamAttitude")
    public JAXBElement<BigInteger> createTeamAttitude(BigInteger value) {
        return new JAXBElement<BigInteger>(_TeamAttitude_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TacticType")
    public JAXBElement<BigInteger> createTacticType(BigInteger value) {
        return new JAXBElement<BigInteger>(_TacticType_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AwayTeamID")
    public JAXBElement<BigInteger> createAwayTeamID(BigInteger value) {
        return new JAXBElement<BigInteger>(_AwayTeamID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RatingLeftAtt")
    public JAXBElement<BigInteger> createRatingLeftAtt(BigInteger value) {
        return new JAXBElement<BigInteger>(_RatingLeftAtt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PossessionSecondHalfAway")
    public JAXBElement<BigInteger> createPossessionSecondHalfAway(BigInteger value) {
        return new JAXBElement<BigInteger>(_PossessionSecondHalfAway_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RatingMidAtt")
    public JAXBElement<BigInteger> createRatingMidAtt(BigInteger value) {
        return new JAXBElement<BigInteger>(_RatingMidAtt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RatingLeftDef")
    public JAXBElement<BigInteger> createRatingLeftDef(BigInteger value) {
        return new JAXBElement<BigInteger>(_RatingLeftDef_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ScorerHomeGoals")
    public JAXBElement<BigInteger> createScorerHomeGoals(BigInteger value) {
        return new JAXBElement<BigInteger>(_ScorerHomeGoals_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ScorerTeamID")
    public JAXBElement<BigInteger> createScorerTeamID(BigInteger value) {
        return new JAXBElement<BigInteger>(_ScorerTeamID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ScorerMinute")
    public JAXBElement<BigInteger> createScorerMinute(BigInteger value) {
        return new JAXBElement<BigInteger>(_ScorerMinute_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TacticSkill")
    public JAXBElement<BigInteger> createTacticSkill(BigInteger value) {
        return new JAXBElement<BigInteger>(_TacticSkill_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArenaName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createArenaName(String value) {
        return new JAXBElement<String>(_ArenaName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserIsSupporter")
    public JAXBElement<BigInteger> createUserIsSupporter(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserIsSupporter_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AwayTeamName")
    public JAXBElement<String> createAwayTeamName(String value) {
        return new JAXBElement<String>(_AwayTeamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RatingMidfield")
    public JAXBElement<BigInteger> createRatingMidfield(BigInteger value) {
        return new JAXBElement<BigInteger>(_RatingMidfield_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserHasClubHouse")
    public JAXBElement<BigInteger> createUserHasClubHouse(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserHasClubHouse_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ScorerPlayerName")
    public JAXBElement<String> createScorerPlayerName(String value) {
        return new JAXBElement<String>(_ScorerPlayerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RatingRightAtt")
    public JAXBElement<BigInteger> createRatingRightAtt(BigInteger value) {
        return new JAXBElement<BigInteger>(_RatingRightAtt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ScorerAwayGoals")
    public JAXBElement<BigInteger> createScorerAwayGoals(BigInteger value) {
        return new JAXBElement<BigInteger>(_ScorerAwayGoals_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FileName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFileName(String value) {
        return new JAXBElement<String>(_FileName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FinishedDate")
    public JAXBElement<String> createFinishedDate(String value) {
        return new JAXBElement<String>(_FinishedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HomeTeamID")
    public JAXBElement<BigInteger> createHomeTeamID(BigInteger value) {
        return new JAXBElement<BigInteger>(_HomeTeamID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MatchID")
    public JAXBElement<BigInteger> createMatchID(BigInteger value) {
        return new JAXBElement<BigInteger>(_MatchID_QNAME, BigInteger.class, null, value);
    }

}
