//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:42:08 AM CEST 
//


package models.fans;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MatchType_QNAME = new QName("", "MatchType");
    private final static QName _Weather_QNAME = new QName("", "Weather");
    private final static QName _FanSeasonExpectation_QNAME = new QName("", "FanSeasonExpectation");
    private final static QName _FetchedDate_QNAME = new QName("", "FetchedDate");
    private final static QName _AwayGoals_QNAME = new QName("", "AwayGoals");
    private final static QName _AwayTeamID_QNAME = new QName("", "AwayTeamID");
    private final static QName _FanMood_QNAME = new QName("", "FanMood");
    private final static QName _UserID_QNAME = new QName("", "UserID");
    private final static QName _Members_QNAME = new QName("", "Members");
    private final static QName _MatchDate_QNAME = new QName("", "MatchDate");
    private final static QName _AwayTeamName_QNAME = new QName("", "AwayTeamName");
    private final static QName _HomeTeamName_QNAME = new QName("", "HomeTeamName");
    private final static QName _SoldSeats_QNAME = new QName("", "SoldSeats");
    private final static QName _HomeGoals_QNAME = new QName("", "HomeGoals");
    private final static QName _TeamID_QNAME = new QName("", "TeamID");
    private final static QName _FanMatchExpectation_QNAME = new QName("", "FanMatchExpectation");
    private final static QName _FileName_QNAME = new QName("", "FileName");
    private final static QName _FanMoodAfterMatch_QNAME = new QName("", "FanMoodAfterMatch");
    private final static QName _Version_QNAME = new QName("", "Version");
    private final static QName _MatchID_QNAME = new QName("", "MatchID");
    private final static QName _HomeTeamID_QNAME = new QName("", "HomeTeamID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Team }
     * 
     */
    public Team createTeam() {
        return new Team();
    }

    /**
     * Create an instance of {@link Match }
     * 
     */
    public Match createMatch() {
        return new Match();
    }

    /**
     * Create an instance of {@link HomeTeam }
     * 
     */
    public HomeTeam createHomeTeam() {
        return new HomeTeam();
    }

    /**
     * Create an instance of {@link PlayedMatches }
     * 
     */
    public PlayedMatches createPlayedMatches() {
        return new PlayedMatches();
    }

    /**
     * Create an instance of {@link AwayTeam }
     * 
     */
    public AwayTeam createAwayTeam() {
        return new AwayTeam();
    }

    /**
     * Create an instance of {@link UpcomingMatches }
     * 
     */
    public UpcomingMatches createUpcomingMatches() {
        return new UpcomingMatches();
    }

    /**
     * Create an instance of {@link HattrickData }
     * 
     */
    public HattrickData createHattrickData() {
        return new HattrickData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MatchType")
    public JAXBElement<BigInteger> createMatchType(BigInteger value) {
        return new JAXBElement<BigInteger>(_MatchType_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Weather")
    public JAXBElement<BigInteger> createWeather(BigInteger value) {
        return new JAXBElement<BigInteger>(_Weather_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FanSeasonExpectation")
    public JAXBElement<BigInteger> createFanSeasonExpectation(BigInteger value) {
        return new JAXBElement<BigInteger>(_FanSeasonExpectation_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FetchedDate")
    public JAXBElement<String> createFetchedDate(String value) {
        return new JAXBElement<String>(_FetchedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AwayGoals")
    public JAXBElement<BigInteger> createAwayGoals(BigInteger value) {
        return new JAXBElement<BigInteger>(_AwayGoals_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AwayTeamID")
    public JAXBElement<BigInteger> createAwayTeamID(BigInteger value) {
        return new JAXBElement<BigInteger>(_AwayTeamID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FanMood")
    public JAXBElement<BigInteger> createFanMood(BigInteger value) {
        return new JAXBElement<BigInteger>(_FanMood_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserID")
    public JAXBElement<BigInteger> createUserID(BigInteger value) {
        return new JAXBElement<BigInteger>(_UserID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Members")
    public JAXBElement<BigInteger> createMembers(BigInteger value) {
        return new JAXBElement<BigInteger>(_Members_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MatchDate")
    public JAXBElement<String> createMatchDate(String value) {
        return new JAXBElement<String>(_MatchDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AwayTeamName")
    public JAXBElement<String> createAwayTeamName(String value) {
        return new JAXBElement<String>(_AwayTeamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HomeTeamName")
    public JAXBElement<String> createHomeTeamName(String value) {
        return new JAXBElement<String>(_HomeTeamName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SoldSeats")
    public JAXBElement<BigInteger> createSoldSeats(BigInteger value) {
        return new JAXBElement<BigInteger>(_SoldSeats_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HomeGoals")
    public JAXBElement<BigInteger> createHomeGoals(BigInteger value) {
        return new JAXBElement<BigInteger>(_HomeGoals_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TeamID")
    public JAXBElement<BigInteger> createTeamID(BigInteger value) {
        return new JAXBElement<BigInteger>(_TeamID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FanMatchExpectation")
    public JAXBElement<BigInteger> createFanMatchExpectation(BigInteger value) {
        return new JAXBElement<BigInteger>(_FanMatchExpectation_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FileName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFileName(String value) {
        return new JAXBElement<String>(_FileName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FanMoodAfterMatch")
    public JAXBElement<BigInteger> createFanMoodAfterMatch(BigInteger value) {
        return new JAXBElement<BigInteger>(_FanMoodAfterMatch_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Version")
    public JAXBElement<BigDecimal> createVersion(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Version_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MatchID")
    public JAXBElement<BigInteger> createMatchID(BigInteger value) {
        return new JAXBElement<BigInteger>(_MatchID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HomeTeamID")
    public JAXBElement<BigInteger> createHomeTeamID(BigInteger value) {
        return new JAXBElement<BigInteger>(_HomeTeamID_QNAME, BigInteger.class, null, value);
    }

}
