//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:42:08 AM CEST 
//


package models.fans;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TeamID"/>
 *         &lt;element ref="{}FanMood"/>
 *         &lt;element ref="{}Members"/>
 *         &lt;element ref="{}FanSeasonExpectation"/>
 *         &lt;element ref="{}PlayedMatches"/>
 *         &lt;element ref="{}UpcomingMatches"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "teamID",
    "fanMood",
    "members",
    "fanSeasonExpectation",
    "playedMatches",
    "upcomingMatches"
})
@XmlRootElement(name = "Team")
public class Team {

    @XmlElement(name = "TeamID", required = true)
    protected BigInteger teamID;
    @XmlElement(name = "FanMood", required = true)
    protected BigInteger fanMood;
    @XmlElement(name = "Members", required = true)
    protected BigInteger members;
    @XmlElement(name = "FanSeasonExpectation", required = true)
    protected BigInteger fanSeasonExpectation;
    @XmlElement(name = "PlayedMatches", required = true)
    protected PlayedMatches playedMatches;
    @XmlElement(name = "UpcomingMatches", required = true)
    protected UpcomingMatches upcomingMatches;

    /**
     * Gets the value of the teamID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTeamID() {
        return teamID;
    }

    /**
     * Sets the value of the teamID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTeamID(BigInteger value) {
        this.teamID = value;
    }

    /**
     * Gets the value of the fanMood property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFanMood() {
        return fanMood;
    }

    /**
     * Sets the value of the fanMood property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFanMood(BigInteger value) {
        this.fanMood = value;
    }

    /**
     * Gets the value of the members property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMembers() {
        return members;
    }

    /**
     * Sets the value of the members property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMembers(BigInteger value) {
        this.members = value;
    }

    /**
     * Gets the value of the fanSeasonExpectation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFanSeasonExpectation() {
        return fanSeasonExpectation;
    }

    /**
     * Sets the value of the fanSeasonExpectation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFanSeasonExpectation(BigInteger value) {
        this.fanSeasonExpectation = value;
    }

    /**
     * Gets the value of the playedMatches property.
     * 
     * @return
     *     possible object is
     *     {@link PlayedMatches }
     *     
     */
    public PlayedMatches getPlayedMatches() {
        return playedMatches;
    }

    /**
     * Sets the value of the playedMatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlayedMatches }
     *     
     */
    public void setPlayedMatches(PlayedMatches value) {
        this.playedMatches = value;
    }

    /**
     * Gets the value of the upcomingMatches property.
     * 
     * @return
     *     possible object is
     *     {@link UpcomingMatches }
     *     
     */
    public UpcomingMatches getUpcomingMatches() {
        return upcomingMatches;
    }

    /**
     * Sets the value of the upcomingMatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpcomingMatches }
     *     
     */
    public void setUpcomingMatches(UpcomingMatches value) {
        this.upcomingMatches = value;
    }

}
