//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.26 at 01:10:39 PM CET 
//


package models;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TotalSumOfBuys"/>
 *         &lt;element ref="{}TotalSumOfSales"/>
 *         &lt;element ref="{}NumberOfBuys"/>
 *         &lt;element ref="{}NumberOfSales"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalSumOfBuys",
    "totalSumOfSales",
    "numberOfBuys",
    "numberOfSales"
})
@XmlRootElement(name = "Stats")
public class Stats {

    @XmlElement(name = "TotalSumOfBuys", required = true)
    protected BigInteger totalSumOfBuys;
    @XmlElement(name = "TotalSumOfSales", required = true)
    protected BigInteger totalSumOfSales;
    @XmlElement(name = "NumberOfBuys", required = true)
    protected BigInteger numberOfBuys;
    @XmlElement(name = "NumberOfSales", required = true)
    protected BigInteger numberOfSales;

    /**
     * Gets the value of the totalSumOfBuys property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalSumOfBuys() {
        return totalSumOfBuys;
    }

    /**
     * Sets the value of the totalSumOfBuys property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalSumOfBuys(BigInteger value) {
        this.totalSumOfBuys = value;
    }

    /**
     * Gets the value of the totalSumOfSales property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalSumOfSales() {
        return totalSumOfSales;
    }

    /**
     * Sets the value of the totalSumOfSales property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalSumOfSales(BigInteger value) {
        this.totalSumOfSales = value;
    }

    /**
     * Gets the value of the numberOfBuys property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfBuys() {
        return numberOfBuys;
    }

    /**
     * Sets the value of the numberOfBuys property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfBuys(BigInteger value) {
        this.numberOfBuys = value;
    }

    /**
     * Gets the value of the numberOfSales property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfSales() {
        return numberOfSales;
    }

    /**
     * Sets the value of the numberOfSales property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfSales(BigInteger value) {
        this.numberOfSales = value;
    }

}
