//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:51:16 AM CEST 
//


package models.transfersteam;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PlayerID"/>
 *         &lt;choice>
 *           &lt;element ref="{}TrainingEvents"/>
 *           &lt;sequence>
 *             &lt;element ref="{}PlayerName"/>
 *             &lt;element ref="{}TSI"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "playerID",
    "trainingEvents",
    "playerName",
    "tsi"
})
@XmlRootElement(name = "Player")
public class Player {

    @XmlElement(name = "PlayerID", required = true)
    protected BigInteger playerID;
    @XmlElement(name = "TrainingEvents")
    protected TrainingEvents trainingEvents;
    @XmlElement(name = "PlayerName")
    protected String playerName;
    @XmlElement(name = "TSI")
    protected BigInteger tsi;

    /**
     * Gets the value of the playerID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPlayerID() {
        return playerID;
    }

    /**
     * Sets the value of the playerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPlayerID(BigInteger value) {
        this.playerID = value;
    }

    /**
     * Gets the value of the trainingEvents property.
     * 
     * @return
     *     possible object is
     *     {@link TrainingEvents }
     *     
     */
    public TrainingEvents getTrainingEvents() {
        return trainingEvents;
    }

    /**
     * Sets the value of the trainingEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainingEvents }
     *     
     */
    public void setTrainingEvents(TrainingEvents value) {
        this.trainingEvents = value;
    }

    /**
     * Gets the value of the playerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * Sets the value of the playerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlayerName(String value) {
        this.playerName = value;
    }

    /**
     * Gets the value of the tsi property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTSI() {
        return tsi;
    }

    /**
     * Sets the value of the tsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTSI(BigInteger value) {
        this.tsi = value;
    }

}
