//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.03.29 at 12:51:16 AM CEST 
//


package models.transfersteam;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SellerTeamID"/>
 *         &lt;element ref="{}SellerTeamName"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sellerTeamID",
    "sellerTeamName"
})
@XmlRootElement(name = "Seller")
public class Seller {

    @XmlElement(name = "SellerTeamID", required = true)
    protected BigInteger sellerTeamID;
    @XmlElement(name = "SellerTeamName", required = true)
    protected String sellerTeamName;

    /**
     * Gets the value of the sellerTeamID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSellerTeamID() {
        return sellerTeamID;
    }

    /**
     * Sets the value of the sellerTeamID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSellerTeamID(BigInteger value) {
        this.sellerTeamID = value;
    }

    /**
     * Gets the value of the sellerTeamName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellerTeamName() {
        return sellerTeamName;
    }

    /**
     * Sets the value of the sellerTeamName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellerTeamName(String value) {
        this.sellerTeamName = value;
    }

}
